# Site settings
title: Life, programming and everything in between
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about programming and life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://basharaj.github.io" # the base hostname & protocol for your site
twitter_username: bashar_aj
github_username:  basharaj

# Build settings
markdown: kramdown
